// <auto-generated />
using Lab5.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab5.Migrations.BookDb
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20260522033538_InitBookDB")]
    partial class InitBookDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab5.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Phúc Nguyễn",
                            CategoryId = 1,
                            ImageUrl = "csharp.jpg",
                            Price = 150.0,
                            Title = "Lập trình C# nâng cao"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Lê Khang",
                            CategoryId = 1,
                            ImageUrl = "efcore.jpg",
                            Price = 120.0,
                            Title = "Nhập môn EF Core"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Nguyễn Nhật Ánh",
                            CategoryId = 2,
                            ImageUrl = "tuoitho.jpg",
                            Price = 80.0,
                            Title = "Cho tôi xin một vé đi tuổi thơ"
                        });
                });

            modelBuilder.Entity("Lab5.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Lập trình"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Cuộc sống"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sức khỏe"
                        });
                });

            modelBuilder.Entity("Lab5.Models.Book", b =>
                {
                    b.HasOne("Lab5.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lab5.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
