// <auto-generated />
using Lab5.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab5.Migrations.BookDb
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20260522035942_UpdateComicData")]
    partial class UpdateComicData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab5.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Eiichiro Oda",
                            CategoryId = 1,
                            ImageUrl = "onepiece.jpg",
                            Price = 25.0,
                            Title = "One Piece Tập 100"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Gosho Aoyama",
                            CategoryId = 1,
                            ImageUrl = "conan.jpg",
                            Price = 22.0,
                            Title = "Thám Tử Lừng Danh Conan Tập 99"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Masashi Kishimoto",
                            CategoryId = 1,
                            ImageUrl = "naruto.jpg",
                            Price = 20.0,
                            Title = "Naruto Tập 1"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Nguyễn Nhật Ánh",
                            CategoryId = 2,
                            ImageUrl = "matbiec.jpg",
                            Price = 85.0,
                            Title = "Mắt Biếc"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Nguyễn Nhật Ánh",
                            CategoryId = 2,
                            ImageUrl = "hoavang.jpg",
                            Price = 90.0,
                            Title = "Tôi Thấy Hoa Vàng Trên Cỏ Xanh"
                        });
                });

            modelBuilder.Entity("Lab5.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Truyện Tranh"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Tiểu Thuyết"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Khoa Học"
                        });
                });

            modelBuilder.Entity("Lab5.Models.Book", b =>
                {
                    b.HasOne("Lab5.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lab5.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
